base/urls.py
from django.urls import path

from . import views

from django.views.generic import TemplateView

app_name = "base"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("firstlogin/", views.FirstLoginView.as_view(), name="first_login"),
    path("profile/", views.profile, name="profile"),
    path("", views.google_login),
    path("preference/", views.preference, name="preference"),
    path('home/create', views.create_offer, name='create_offer'),
    path("transfer/", views.first_login, name="transfer"),
    path('home/<int:pk>/', views.show_task, name='TaskView'),
    path('volunteer/', views.VolunteerView.as_view(), name='Volunteer'),
    path('donate/', views.DonateView.as_view(), name='Donate'),
    path("donate/transaction/<int:pk>/", views.transaction, name="transaction"),
    path("<args>/donate/success/<int:pk>/", views.success, name="success"),
    path("volunteer/confirmation<int:pk>/", views.vsuccess, name="vsuccess"),
    path("about", views.AboutView.as_view(), name="about"),
    path("profile/edit", views.edit_profile, name="edit"),
    path("profile/edit-profile", views.save_edit, name="edit_profile"),
    path("schedule/", views.schedule, name='schedule'),
    path('schedule/<int:pk>/', views.accepted_task, name='accepted_task'),
    path('submitted-events/', views.submitted_events, name='submitted_events'),
    path('submitted-events/<int:pk>/', views.submitted_volunteer_view, name='submitted_volunteer_view'),
    path('leaderboard/', views.LeaderboardView.as_view(), name='leaderboard'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include('base.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError

#makes sure duration of event is at least 1 minute
def valid_duration(duration):
    if duration > 0:
        return duration
    else:
        raise ValidationError("Please enter a valid duration for the event in the number of minutes it will take to complete")

#Extension of User model through OneToOneField
class Create(models.Model):
    Name = models.CharField(max_length=50)
    Description = models.TextField(max_length=300)
    Date = models.DateField(blank=True, null=True)
    Time = models.TimeField(blank=True, null=True)
    #type = [('Volunteer', 'Volunteer'), ('Donation', 'Donation')]
    Event = models.TextField(max_length=10)#, choices=type)
    xp = models.IntegerField(default=10)
    Datetime = models.DateTimeField(blank=True, null=True)
    duration = models.TextField(blank=True, null=True)

    #list of those who have signed up for event
    signup_list = models.ManyToManyField(User, blank=True)

    #total amount received if donation event
    amount_received = models.FloatField(default=0.0)

    def __str__(self):
        return self.Description

    def get_author(self):
        return self.Name

    def get_type(self):
        return self.Event

#how to extend profile model from User from tutorial at https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_login = models.BooleanField(default=True)
    phoneNum = models.CharField(max_length=20, blank=True)
    exp = models.IntegerField(default=0)
    level = models.IntegerField(default=0) # Unsure if this will actually be used, not important at the moment.
    event_history = models.ManyToManyField(Create, related_name='event_history')

    #list of events submitted by user
    submitted_volunteer = models.ManyToManyField(Create, related_name='submitted_volunteer')
    submitted_donation = models.ManyToManyField(Create, related_name='submitted_donation')

    #true if user is a volunteer, false otherwise
    is_volunteer = models.BooleanField(default=True)

#automatically save and create Profile when User is created or modified
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

base/forms.py
from .models import Create, Profile
from django import forms


class CreateForm(forms.ModelForm):
    class Meta:
        model = Create
        fields = ('Name', 'Description', 'Event', 'Date', 'Time', 'duration')

base/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from django.views import generic

from .models import Profile
from .forms import CreateForm
from .models import Create

from django.core.mail import EmailMessage
from django.conf import settings

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

import datetime
from datetime import date
from django.utils import timezone

import stripe

stripe.api_key = "sk_test_51Hi3ccIhinpgN0d6E5B0qQhpblefy2DpeJEsa3Ctw8K5B0CN8J8rbziZBfDYwmiInTgFaSlyn8I6lmmUKDhDsBh100Woe7EF7v"

class FirstLoginView(LoginRequiredMixin, generic.TemplateView):
    model = Profile
    template_name = 'base/first_login.html'
    context_object_name = "profile"

    raise_exception = True  # Raise exception when no access instead of redirect
    permission_denied_message = "You must login first."


class HomeView(LoginRequiredMixin, generic.ListView):
    model = Create
    template_name = 'base/home.html'
    context_object_name = "event_list"

    raise_exception = True  # Raise exception when no access instead of redirect
    permission_denied_message = "You must login first."

    def get_queryset(self):
        now = timezone.now()
        return Create.objects.filter(Datetime__gte=now).order_by('Datetime')
        #return Create.objects.all().filter(Datetime__gte=datetime.datetime.now())


class VolunteerView(LoginRequiredMixin, generic.ListView):
    model = Create
    template_name = 'base/volunteer_view.html'
    context_object_name = "event_list"

    raise_exception = True  # Raise exception when no access instead of redirect
    permission_denied_message = "You must login first."

    def get_queryset(self):
        now = timezone.now()
        return Create.objects.all().filter(Event='Volunteer').filter(Datetime__gte=now).order_by('Datetime')

class DonateView(LoginRequiredMixin, generic.ListView):
    model = Create
    template_name = 'base/donate_view.html'
    context_object_name = "event_list"

    raise_exception = True  # Raise exception when no access instead of redirect
    permission_denied_message = "You must login first."

    def get_queryset(self):
        now = timezone.now()
        return Create.objects.all().filter(Event='Donation').filter(Datetime__gte=now).order_by('Datetime')

class AboutView(LoginRequiredMixin, generic.TemplateView):
    model = Profile
    template_name = 'base/about.html'

class LeaderboardView(LoginRequiredMixin, generic.ListView):
    model = Profile
    template_name = 'base/leaderboard.html'

    raise_exception = True  # Raise exception when no access instead of redirect
    permission_denied_message = "You must login first."

    def get_queryset(self):
        return Profile.objects.all().order_by('-exp')[:10]

@login_required
def first_login(request):
    Profile.objects.get_or_create(user=request.user)
    #if first time logging in, redirect to first login page instead of home
    if not request.user.profile.first_login:
        return HttpResponseRedirect(reverse("base:home"))

    request.user.profile.first_login = False
    request.user.save()
    return render(request, "base/first_login.html")

#tutorial for google login followed from https://whizzoe.medium.com/in-5-mins-set-up-google-login-to-sign-up-users-on-django-e71d5c38f5d5
def google_login(request):
    return render(request, "base/index.html")


@login_required
def signout(request):
    logout(request)
    return render(request, "base/index.html")


@login_required
def profile(request):
    request.user.profile.level = request.user.profile.exp // 1000
    event_history = request.user.profile.event_history.all()
    return render(request, 'base/profile.html', {'events': event_history})

@login_required()
def schedule(request):
    now = timezone.now()
    schedule = request.user.profile.event_history.all().filter(Event='Volunteer').filter(Datetime__gte=now)
    return render(request, 'base/schedule.html', {'schedule': schedule})

@login_required()
def accepted_task(request, pk):
    task = Create.objects.get(pk=pk)
    return render(request, 'base/accepted_task.html', {
        'event': task
    })

#After user logs in first time, they submit their preference for how they want to use site
@login_required()
def preference(request):
    #checks if user wants to be a volunteer, submitting otherwise
    if request.POST["Preference"] == "Volunteer":
        request.user.profile.is_volunteer = True
    else:
        request.user.profile.is_volunteer = False

    request.user.save()
    return HttpResponseRedirect(reverse("base:home"))

@login_required()
def create_offer(request):
    if request.user.profile.is_volunteer == True:
        messages.info(request, ('Sorry! The create page is not for volunteers and is only for submitters!'))
        return HttpResponseRedirect(reverse("base:home"))
    #post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        event = Create()
        event.Name = request.POST['Name']
        event.Description = request.POST['Description']
        event.Event = request.POST['Event']
        event.Date = request.POST['Date']
        event.Time = request.POST['Time']
        event.duration = request.POST['duration']
        event.Datetime = datetime.datetime.strptime(event.Date + " " + event.Time, "%Y-%m-%d %H:%M")
        #scale xp earned to duration of event if event is for volunteering
        if event.Event == 'Volunteer':
            event.xp = event.xp * int(event.duration)
            email = EmailMessage(
                "Successful Submitted Opportunity",
                'Dear ' + request.user.first_name + ",\n\nThank you for submitting the opportunity \"" + event.Name + "\"! To inform the volunteer(s) "
                "of any further details of the event (such as location, important updates, etc.), be sure to find the contacts of "
                "each of the volunteers under the \"Submitted Events\" tab on our site and then clicking the opportunity you created. "
                "\n\nSincerely,\nTeam Split Coin",
                'teamsplitcoin@gmail.com',
                [request.user.email],
            )
            email.fail_silently = False
            email.send()
        event.save()
        if event.Event == 'Volunteer':
            request.user.profile.submitted_volunteer.add(event)
        else:
            request.user.profile.submitted_donation.add(event)
            email = EmailMessage(
                "Successful Submitted Opportunity",
                'Dear ' + request.user.first_name + ",\n\nThank you for submitting the opportunity \"" + event.Name +
                "\"! To view how much money you have received for this donation opportunity, be sure to view the \"Submitted Events\" "
                "tab on our site and view the opportunity you have just created."
                "\n\nSincerely,\nTeam Split Coin",
                'teamsplitcoin@gmail.com',
                [request.user.email],
            )
            email.fail_silently = False
            email.send()
        return HttpResponseRedirect(reverse("base:home"))
    return render(request, 'base/create.html')

@login_required()
def show_task(request, pk):
    task = Create.objects.get(pk=pk)
    return render(request, 'base/task_view.html', {
        'event': task
    })

@login_required
def transaction(request, pk):
    if request.method == "POST":
        amount = float(request.POST['amount'])

        #from Stripe API
        customer = stripe.Customer.create(
            email = request.user.email,
            name = request.user.first_name,
            source = "tok_visa",
        )
        charge = stripe.Charge.create(
            customer = customer,
            amount = int(amount*100),
            currency = "usd",
            description = "Donation",
        )

        event = Create.objects.get(pk=pk)

        #scale xp earned to amount donated
        request.user.profile.exp += int(event.xp * amount)
        request.user.profile.level = request.user.profile.exp // 1000
        request.user.profile.event_history.add(event)

        event.amount_received += amount
        event.save()

        request.user.save()

    return redirect("base:success", args=amount, pk=pk)


@login_required()
def vsuccess(request, pk):
    if request.method == "POST":
        event = Create.objects.get(pk=pk)
        event.signup_list.add(request.user)

        if event in request.user.profile.event_history.all():
            messages.info(request, ('Sorry! You have already signed up for this event!'))
            return render(request, "base/vsuccess.html")

        email = EmailMessage(
            'Successful Volunteer Sign-Up',
            'Dear ' + request.user.first_name + ",\n" +
            "\nThank you for signing up for a volunteering opportunity! Here are the details of the event:" +
            "\n\nDate of event: " + str(event.Date) +
            "\nTime of event: " + str(event.Time) +
            "\nName of event: " + event.Name +
            "\nEvent description: " + event.Description +

            "\n\nSincerely,\nTeam Split Coin",
            'teamsplitcoin@gmail.com',
            [request.user.email],
        )
        email.fail_silently = False
        email.send()
        request.user.profile.exp += event.xp
        request.user.profile.level = request.user.profile.exp // 1000
        request.user.profile.event_history.add(event)

        request.user.save()
        event.save()

        return render(request, "base/vsuccess.html")


@login_required()
def success(request, args, pk):
    amount = args
    email = EmailMessage(
        'Successful Donation',
        'Dear ' + request.user.first_name + ",\n\nThank you for your $" + amount + " donation! \n\nSincerely,\nTeam Split Coin",

base/templates/base/donate_view.html
<!DOCTYPE html>
<html>
  <head>
    <title>Google Registration</title>
    <div class="jumbotron">
      <h1><p style="font-size:50px;">SPLIT COIN</p></h1>
    </div>
  </head>
  <body>

<!-- Setting up UI -->

<!-- CSS for the Navbar and stuff -->
<style>
  .topnav {
    background-color: #2B7A78;
    overflow: hidden;
  }
  
  html,body {
    background-color: #3AAFA9;
  }
  
  .topnav a {
    float: left;
    color: #17252A;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }
  
  /* Add a color to the hovered link */
  .topnav a:hover {
    background-color: #DEF2F1;
    color: #17252A;
  }
  
  /* Add a color to the active/current link */
  .topnav a.active {
    background-color: #DEF2F1;
    color: #17252A;
  }
  
  .jumbotron{
    margin: auto;
    font-size: 50px;
    width: 50%;
    border: 0px solid #73AD21;
    color: #17252A;
    text-align: center;
  }
  
  .footer{
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      background-color: #333;
      color:rgb(252, 248, 2);
      text-align: center;
  }
  
  .eventTemplate{
  margin: auto;
  width: 60%;
  border: 2px solid;
  border-radius: 25px;
  display: flex;
  flex-direction: row;
  }
  
  .eventElement1{
  border-right: 2px solid;
  flex: 3;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  }
  
  .eventElement3{
  border-bottom: 2px solid;
  display: flex;
  justify-content: space-between;
  padding: 0px 10px;
  }
  
  .eventElement4{
  text-align: left;
  }
  
  a:link {
    color: #17252A;
    background-color: transparent;
    text-decoration: none;
  }
  
  a:visited {
    color: #17252A;
    background-color: transparent;
    text-decoration: none;
  }
  
  a:hover {
    color: #17252A;
    background-color: transparent;
    text-decoration: none;
  }
  
  a:active {
    color: #17252A;
    background-color: transparent;
    text-decoration: underline;
  }
  
  .subheader{
  text-align: center;
  margin: auto;
  width: 50%;
  border: 0px solid
}

  .tab { text-indent:30px }
  
  img {border-radius: 0px 25px 25px 0px;}
  h1 {color: white;}
  p {color: white; font-size: 20px;}
  
  </style>

<!-- The (hopefully) functioning Navbar -->
<div class="topnav">
  <a href="/home">Home</a>
  <a class="active" href="/donate">Donate</a>
  <a href="/volunteer">Volunteer</a>
  <a href="/schedule">Schedule</a>
  <a href="/profile">Profile</a>
  <a href="/leaderboard">Leaderboard</a>
  <a href="/about">About</a>
    {% if user.profile.is_volunteer == False %}
    <a href="/home/create">Create</a>
    <a href="/submitted-events">Submitted Events</a>
    {% endif %}
  <a style="float:right" href="/accounts/logout">Logout</a>
</div>

<h1 class="subheader"> All Donation Offers </h1>
<br>

<div align="center">
{% block content %}
{% for event in event_list %}
<div class="eventTemplate">
  <div class="eventElement1">
    <div class="eventElement3" style="font-size: 30px;">
       
         <a class="title" style="color: white" href="{% url 'base:TaskView' event.id %}"> {{ event.Name }} </a>
       <div style="color: white">
          {{ event.Date }} at {{event.Time }}
       </div>
    </div>

    <div class="eventElement4">
      <p class="tab" style="color: white"> {{ event.Description }} </p>
    </div>

    </div>

  <div class="eventElement2" style="display:flex;">
    <a class="picture" href="{% url 'base:TaskView' event.id %}" style="display:flex;">  <img src="https://lh3.googleusercontent.com/proxy/ze8OV6CflH0uQ8VmPxf6bqOJw0VVoyHH5APJVFDzzC4Icxikq1S8PWa42q0W4_HNc0vSzb728_EpXW6nZqdzRUR9yDmIt8xcl94PMUgO5YrX82cye2RXQgBsUA" alt="Cartoon Coin" width="200" height="200">  </a>
  </div>
</div>
<br>
  <br>
{% empty %}
    <p>There are no offers yet.</p>
{% endfor %}
{% endblock %}
</div>
<br>
<br>
<br>
  <div class="footer">
    <p> All Rights Reserved © Copyright 2020 Team 1-39 </p>
    </div>

  </body>
</html>

base/templates/base/task_view.html
<!-- from Stripe API used for donations in which they provide the code for developers: https://stripe.com/docs/stripe-js. -->
<style type="text/css">
    /**
     * The CSS shown here will not be introduced in the Quickstart guide, but shows
     * how you can use CSS to style your Element's container.
     */
    .StripeElement {
      box-sizing: border-box;

      height: 40px;

      padding: 10px 12px;

      border: 1px solid transparent;
      border-radius: 4px;
      background-color: white;

      box-shadow: 0 1px 3px 0 #e6ebf1;
      -webkit-transition: box-shadow 150ms ease;
      transition: box-shadow 150ms ease;
    }

    .StripeElement--focus {
      box-shadow: 0 1px 3px 0 #cfd7df;
    }

    .StripeElement--invalid {
      border-color: #fa755a;
    }

    .StripeElement--webkit-autofill {
      background-color: #fefde5 !important;
    }
</style>

<!DOCTYPE html>
<html>
  <head>
    <title>Google Registration</title>
    <div class="jumbotron">
      <h1><p style="font-size:50px;">SPLIT COIN</p></h1>
    </div>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'base/style.css' %}?version=1">
  </head>


  <body>

<!-- CSS for the Navbar and stuff -->
<style>
  .topnav {
    background-color: #2B7A78;
    overflow: hidden;
  }
  
  html,body {
    background-color: #3AAFA9;
  }
  
  .topnav a {
    float: left;
    color: #17252A;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }
  
  /* Add a color to the hovered link */
  .topnav a:hover {
    background-color: #DEF2F1;
    color: #17252A;
  }
  
  /* Add a color to the active/current link */
  .topnav a.active {
    background-color: #DEF2F1;
    color: #17252A;
  }
  
  .jumbotron{
    margin: auto;
    font-size: 50px;
    width: 50%;
    border: 0px solid #73AD21;
    color: #17252A;
    text-align: center;
  }

  .subheader{
  text-align: center;
  margin: auto;
  width: 50%;
  border: 0px solid
}
.footer{
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    background-color: #333;
    text-align: center;
}
  
  .eventTemplate{
  margin: auto;
  width: 50%;
  border: 2px solid;
  border-radius: 25px;
  display: flex;
  flex-direction: row;
  }
  
  .eventElement1{
  border-right: 2px solid;
  flex: 3;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  }
  
  .eventElement3{
  border-bottom: 2px solid;
  display: flex;
  justify-content: space-between;
  padding: 0px 10px;
  }
  
  .VolunteerEventPage
  {
    border: 2px solid;
    font-size: 30px;
    width: 40%;
    margin: auto;
  }
  .eventElement4{
  text-align: left;
  }
  
  a:link {
    color: #17252A;
    background-color: transparent;
    text-decoration: none;
  }
  
  a:visited {
    color: #17252A;
    background-color: transparent;
    text-decoration: none;
  }
  
  a:hover {
    color: #17252A;
    background-color: transparent;
    text-decoration: none;
  }
  
  a:active {
    color: #17252A;
    background-color: transparent;
    text-decoration: underline;
  }
  
  .tab { text-indent:30px }
  
  img {border-radius: 0px 25px 25px 0px;}
  h1 {color: white;}
  p {color: white; font-size: 20px;}
  
  </style>

<!-- The (hopefully) functioning Navbar -->
<div class="topnav">
    <a href="/home">Home</a>
    <a href="/donate">Donate</a>
    <a href="/volunteer">Volunteer</a>
    <a href="/schedule">Schedule</a>
    <a href="/profile">Profile</a>
    <a href="/leaderboard">Leaderboard</a>
    <a href="/about">About</a>
    {% if user.profile.is_volunteer == False %}
    <a href="/home/create">Create</a>
    <a href="/submitted-events">Submitted Events</a>
    {% endif %}
    <a style="float:right" href="/accounts/logout">Logout</a>
</div>
<br>
<h1 class="subheader" align="center"> Do you want to accept this offer? </h1>
<br>

{% block content %}
<div class="VolunteerEventPage"  align="center">
    <strong >{{ event.Name }}</strong>
    <strong>({{ event.Event }})</strong>
    <br>
    <p style="padding-top: 10px; font-size: 30px;">When: {{ event.Date }} at {{ event.Time }}</p>
    {% if event.Event == "Volunteer" %}
    <p style="padding: 10px; font-size: 30px;">Duration: {{ event.duration }} minutes</p>
    {% endif %}
    <div style="border-top: 2px solid; padding: 10px; font-size: 30px; text-align: left;" class="VolunteerViewDesc">
    <p> {{ event.Description|linebreaks }}</p>
    </div>
</div>
    {% if event.Event == "Volunteer" %}
        <form action="{% url 'base:vsuccess' event.pk %}" method="post" id="accept-offer">{% csrf_token %}
            <div align="center"><button>Accept</button></div>
        </form>
    {% endif %}
    {% if event.Event == "Donation" %}
        <script src="https://js.stripe.com/v3/"></script>
        <form action="{% url 'base:transaction' event.pk %}" method="post" id="payment-form">{% csrf_token %}

            <!-- code for donation box instead of slider
            <br>
            <br>
            <div class="form-group" align="center">
                <label>Amount to donate in USD($)</label>
                <input type="text" class="form-control" name = "amount">
                <small class="form-text text-muted">Enter how much you would like to donate up to two decimal places.</small>
            </div>
            -->
            <br>
            <h2 align="center">Select how much you would like to donate in USD($)</h2>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>

            <br>
            <div class="main" style="width:90%;">
                <input type="range" min="0.5" max="100" value="50" id="slider" step="0.25" name="amount">
                <div id="selector">
                    <div class="SelectBtn"></div>
                    <div id="SelectValue"></div>
                </div>
                <div id="ProgressBar"></div>
            </div>
            <br>
            <!-- <small class="form-text text-muted">Enter how much you would like to donate.</small> -->

            <!-- for donation slider from tutorial at https://www.youtube.com/watch?v=Ow0QjqmaRtQ&ab_channel=EasyTutorials -->
            <script>
                var slider = document.getElementById("slider");
                var selector = document.getElementById("selector");
                var SelectValue = document.getElementById("SelectValue");
                var ProgressBar = document.getElementById("ProgressBar");

                SelectValue.innerHTML = "$" + slider.value;

                slider.oninput = function(){
                    SelectValue.innerHTML = "$" + this.value;
                    selector.style.left = this.value + "%";
                    ProgressBar.style.width = this.value + "%";
                }
            </script>

            <br>
            <!-- From Stripe API -->
            <div class="form-row">
                <label for="card-element">
                Credit or debit card
              </label>
              <div id="card-element">
                <!-- A Stripe Element will be inserted here. -->
              </div>

              <!-- Used to display form errors. -->
              <div id="card-errors" role="alert"></div>
            </div>
            <div align="center"><button>Submit Payment</button></div>
            <br>
        </form>
        <h3>Note: This donation system does not actually charge a real card; it automatically charges a testing card so as to avoid
        mischarges. You can enter any credit card information you like, although the expiration date must be in the future. If you prefer,
        you can use a knowingly faulty credit card number that is in Mastercard or Visa format; the system will automatically charge
        a test card no matter what credit card number you enter. Alternatively, "4242 4242 4242 4242" with any future expiration date
            and any CVC works as that is the pseudo-card we are charging. You may refer to <a style="text-decoration: underline; color: #0000FF" href=https://stripe.com/docs/testing>this link</a>
        for more information about what we are using for donations.</h3>
    {% endif %}
{% endblock %}

<br>
<br>
<br>

<div class="footer" style="padding-top: 20px; padding-bottom: 20;">
  <p> All Rights Reserved © Copyright 2020 Team 1-39 </p>
  </div>

  </body>
</html>

<!-- from Stripe API: https://stripe.com/docs/stripe-js. -->
<script>
    // Create a Stripe client.
    var stripe = Stripe('pk_test_51Hi3ccIhinpgN0d6Q79Qyavo5iHHJC9mAq0Hg1uPE8jBNXbwAr8PuaSXrlgL4rGULahJWeGzNaEq0XUI2HhCUr4800ADTdVk6G');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
      base: {
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
          color: '#aab7c4'
        }
      },
      invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
      }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.on('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = '';
      }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();

      stripe.createToken(card).then(function(result) {
        if (result.error) {
          // Inform the user if there was an error.
          var errorElement = document.getElementById('card-errors');
          errorElement.textContent = result.error.message;
        } else {
          // Send the token to your server.
          stripeTokenHandler(result.token);
        }
      });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
      // Insert the token ID into the form so it gets submitted to the server
      var form = document.getElementById('payment-form');
      var hiddenInput = document.createElement('input');
      hiddenInput.setAttribute('type', 'hidden');
      hiddenInput.setAttribute('name', 'stripeToken');
      hiddenInput.setAttribute('value', token.id);
      form.appendChild(hiddenInput);

      // Submit the form
      form.submit();
    }
</script>